spring:
  config:
    import: "optional:classpath:application-secrets.yml"
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  game-history:
    max-count: 10
  openAi:
    maxToken: 2000
    temperature: 0.5
    model: gpt-4.1-mini
    prompt-commentary: |
      À partir des données d'événements et des stats d'une partie (JSON fourni), génère un commentaire pour le joueur dont le pseudo est dans "pseudoFocusedPlayer".
      Tu peux voir s'il a gagné la partie via la variable win dans les participants si tu compares puuid et puuidFocusedPlayer
      Nommer ce joueur par son pseudo.
      Nommer les autres joueurs par leur champions
      Décris les actions importantes, les moments clés et l'impact stratégique du joueur sans énumérer bêtement tous les scores de chacun
      Résume clairement sa performance, son style de jeu, son rôle dans la partie et sa performance comparée à ses équipiers
      Maximum 1000 caractères.
